### ISSUE TITLE
How to login?!!!

### ISSUE THREAD

**Issue by bleudev** [cshuaimin/uva#5]
I installed uva, but don't understand how to log in. Terminal gives message: `you are not logged in yet`. I didn't find command to log in. Can you, please, help me?

**Comment by bleudev** [comment]
If you need, i will publish screenshot

![image](https://github.com/user-attachments/assets/7dbef834-9bed-4c7e-91b3-b4997401cead)

**Comment by cshuaimin** [comment]
You need to run `uva user -l`, run `uva user -h` for help.

I don't know if this tool still works yet, because I haven't used it for years.

**Comment by bleudev** [comment]
> You need to run `uva user -l`, run `uva user -h` for help.
> 
> I don't know if this tool still works yet, because I haven't used it for years.

Thanks, it works!
